# Generated by Django 5.2.17 on 2026-08-20 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='kildenøgle')),
                ('source_row', models.PositiveIntegerField(blank=True, editable=False, help_text='Kun til fejlsøgning. Rækker flytter sig, når regnearket sorteres.', null=True, verbose_name='række i regnearket')),
                ('submitted_at', models.DateTimeField(help_text='Tidsstemplet fra formularen.', verbose_name='indsendt')),
                ('applicant_name', models.CharField(blank=True, max_length=200, verbose_name='ansøger')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='telefon')),
                ('answers', models.JSONField(default=list, help_text="Alle formularens svar, i formularens rækkefølge: [{'question': ..., 'value': ...}].", verbose_name='svar')),
                ('search_text', models.TextField(blank=True, editable=False, verbose_name='søgetekst')),
                ('status', models.CharField(choices=[('new', 'Ny'), ('in_progress', 'I gang'), ('saved', 'Gemt til senere'), ('rejected', 'Afvist'), ('finished', 'Afsluttet')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='Gør det muligt at se, hvor længe en ansøgning har stået stille.', null=True, verbose_name='status ændret')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5. Tom betyder ikke vurderet, hvilket ikke er det samme som 1.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='vurdering')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='importeret')),
                ('synced_at', models.DateTimeField(blank=True, help_text='Sidste gang formularens svar blev læst ind på denne ansøgning.', null=True, verbose_name='senest synkroniseret')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='opdateret')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='ansvarlig')),
            ],
            options={
                'verbose_name': 'erhvervsansøgning',
                'verbose_name_plural': 'erhvervsansøgninger',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='skrevet')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shoprentals.application', verbose_name='ansøgning')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_comments', to=settings.AUTH_USER_MODEL, verbose_name='skrevet af')),
            ],
            options={
                'verbose_name': 'kommentar',
                'verbose_name_plural': 'kommentarer',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='virksomhedsnavn')),
                ('cvr', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='CVR-nummer skal være otte cifre.', regex='^\\d{8}$')], verbose_name='CVR-nummer')),
                ('legal_form', models.CharField(blank=True, help_text='F.eks. ApS, A/S, enkeltmandsvirksomhed.', max_length=64, verbose_name='selskabsform')),
                ('company_address', models.TextField(blank=True, verbose_name='virksomhedens adresse')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='kontaktperson')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='kontaktemail')),
                ('contact_phone', models.CharField(blank=True, max_length=64, verbose_name='kontakttelefon')),
                ('unit_label', models.CharField(blank=True, help_text="Hvilket lejemål ansøgningen gælder, f.eks. 'Jægergade 4, kld.'.", max_length=120, verbose_name='lejemål')),
                ('purpose', models.TextField(blank=True, help_text='Hvad lejemålet må bruges til. Står i kontrakten, så vær konkret.', verbose_name='anvendelse')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='areal (m²)')),
                ('annual_rent_dkk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='årlig leje (kr.)')),
                ('deposit_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='depositum (måneder)')),
                ('lease_start', models.DateField(blank=True, null=True, verbose_name='ønsket overtagelse')),
                ('notes', models.TextField(blank=True, help_text='Aftaler og forbehold, der ikke passer i felterne ovenfor.', verbose_name='noter til advokaten')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='opdateret')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shoprentals.application', verbose_name='ansøgning')),
            ],
            options={
                'verbose_name': 'kontraktoplysninger',
                'verbose_name_plural': 'kontraktoplysninger',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-submitted_at'], name='shoprentals_status_7b3d9b_idx'),
        ),
    ]
