# Generated by Django 5.2.17 on 2026-08-13 08:40

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='private_booking_horizon_days',
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='private_booking_max_horizon_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='And no more than this many days ahead. 90 ≈ three months.', verbose_name='private booking horizon (days)'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='private_booking_min_notice_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Residents must book at least this many days ahead.', verbose_name='private booking notice (days)'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='private_booking_weekdays',
            field=models.JSONField(default=apps.bookings.models.all_weekdays, help_text='Weekdays a private booking may start on. 0 = Monday, 6 = Sunday.', verbose_name='private booking weekdays'),
        ),
    ]
