# Generated by Django 5.2.17 on 2026-09-16 20:23

from django.db import migrations, models


def seed_from_the_first_occurrence(apps, schema_editor):
    """Give existing series a pattern origin.

    They were generated from their first occurrence, so that is where the
    pattern began. Only wrong for a series whose first evening has since been
    moved by hand, which is exactly the drift the column exists to stop — and
    there is nothing better to recover it from.
    """
    EventSeries = apps.get_model("bookings", "EventSeries")
    for series in EventSeries.objects.all():
        first = series.occurrences.order_by("start").first()
        if first is None:
            continue
        series.seed_start = first.start
        series.seed_end = first.end
        series.save(update_fields=["seed_start", "seed_end"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookingsettings_private_booking_horizon_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='seed_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pattern end'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='seed_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pattern start'),
        ),
        migrations.RunPython(seed_from_the_first_occurrence, migrations.RunPython.noop),
    ]
