# Generated by Django 5.2.17 on 2026-09-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_eventseries_seed_end_eventseries_seed_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='public_bookings_open',
            field=models.BooleanField(default=False, help_text="When off, only the beboerlokalegruppe and admins may create a public booking. Booking one in someone else's name stays restricted to them even once this is turned on.", verbose_name='public bookings open to everyone'),
        ),
    ]
