# Generated by Django 5.2.17 on 2026-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingsettings_public_bookings_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReminderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='When off, no reminders are sent.', verbose_name='send reminders')),
                ('subject', models.CharField(default='Påmindelse: du har beboerlokalet i morgen', max_length=200, verbose_name='subject')),
                ('body', models.TextField(default='Kære nabo!\n\nDu har booket beboerlokalet til dit private arrangement i morgen fra klokken {start} til klokken {slut}.\nHer følger lidt praktiske informationer om brugen af lokalet.\n\n## Generelt\nDu låser dig ind i lokalet vha. den blå vaskebrik. Når du går, skal du huske at lukke vinduerne, tjekke at bagdøren er låst og at slukke alle tændte apparater.\n\nLokalet må forventes at blive overtaget i brugt stand, men det skal afleveres opryddet og rengjort (se nedenfor). På denne måde sikrer vi, at lokalet jævnligt rengøres.\n\nSom altid skal man udvise respekt for naboerne. Har du et aftenarrangement skal du huske, at der skal være stille kl. 22, og at arrangementet senest skal være slut kl. 00.00. Derudover skal husordenen overholdes (se husordenen her: https://usercontent.one/wp/ab-jaeger.dk/wp-content/uploads/Husorden-AB-Jaeger-maj-2024.pdf)\n\n## Oprydning\nDa vi ikke har rengøringspersonale, lader vi det være op til de private arrangementer at gøre lokalet rent. Derfor skal du efter brug sørge for, at køkkenet, toilettet og gulvet er gjort rent, at opvasken er taget, og at der er blevet smidt skrald ud. Sørg derudover for, at borde og stole er sat tilbage på plads.\n\n## Faciliteter\nDer er internet i lokalet, og koden og netværksnavnet hænger over garderoben. Projektoren kan benyttes ved at tænde den med den store hvide fjernbetjening, og herefter kan du enten bruge Google TV (styres med den lille hvide fjernbetjening), blu-ray-afspilleren eller selv tilslutte en computer via HDMI-stikket i vindueskarmen.\n\nKøkkenet er desværre fortsat under opbygning, og kan derfor ikke bruges, som det er nu.\n\nTil private arrangementer er det ikke tilladt at bruge lokalets kaffe, te og sodavand. Her skal du selv medbringe drikkevarer og mad.\n\n## Valgfri betaling\nDet er gratis at låne lokalet, men det er ikke gratis at drive lokalet. Vi håber derfor, hvis du har råd til det, at du vil betale et valgfrit beløb via MobilePay til nummeret 121714. Det hjælper nemlig med at finansiere indkøb af alt fra toiletpapir til opvaskemiddel, samt elektricitet, varme, vedligehold og så videre - og så kan vi blive ved at holde lokalet gratis og åbent :)\n\n## Kontakt\nHvis du har spørgsmål, så er du velkommen til at skrive til os på beboerlokale@ab-jaeger.dk.\n\nGod fornøjelse med dit arrangement!\n\nMed venlig hilsen\nbeboerlokalegruppen\nSine, Jørn, Fatima, Jonas og Andreas', help_text='Placeholders: {navn} (first name), {dato} (the day), {start} and {slut} (times). A blank line starts a new paragraph; a paragraph starting with ## is a heading. Web addresses become links.', verbose_name='text')),
            ],
            options={
                'verbose_name': 'booking reminder email',
                'verbose_name_plural': 'booking reminder email',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='reminder sent at'),
        ),
    ]
