# Generated by Django 5.2.17 on 2026-08-10 21:53

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Optional. Shown as contact info on bookings when provided.', max_length=32, verbose_name='phone number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='street')),
                ('house_number', models.CharField(help_text="Entrance number, e.g. '12' or '12A'.", max_length=16, verbose_name='house number')),
                ('name', models.CharField(blank=True, help_text="Optional internal name, e.g. 'Blok A'.", max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'ordering': ['street', 'house_number'],
                'constraints': [models.UniqueConstraint(fields=('street', 'house_number'), name='unique_building_address')],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.BigIntegerField(help_text="The user's ID in the association's other database.", unique=True, verbose_name='external user ID')),
                ('resident_number', models.CharField(help_text='Format: 1-2345-6789-0.', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Beboernummer skal have formatet 1-2345-6789-0.', regex='^\\d-\\d{4}-\\d{4}-\\d$')], verbose_name='resident number')),
                ('floor', models.CharField(help_text="E.g. 'st.', '1', '2'. Use 'kl.' for basement.", max_length=8, verbose_name='floor')),
                ('door', models.CharField(blank=True, help_text="E.g. 'th', 'tv', 'mf', or a door number. Blank if the floor is one flat.", max_length=16, verbose_name='door')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='accounts.building', verbose_name='building')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'resident',
                'verbose_name_plural': 'residents',
                'ordering': ['building', 'floor', 'door'],
            },
        ),
    ]
