# Generated by Django 5.2.17 on 2026-08-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Kopi af den oprettede brugers email, så rækken overlever en afvisning.', max_length=254, verbose_name='email')),
                ('claimed_address', models.CharField(help_text='Fritekst, som ansøgeren skrev den. Sammenholdes med beboerregistret i hånden.', max_length=255, verbose_name='oplyst adresse')),
                ('claimed_resident_number', models.CharField(blank=True, help_text='Valgfrit, og bevidst ikke formatvalideret. Hjælper med at finde personen.', max_length=32, verbose_name='oplyst beboernummer')),
                ('status', models.CharField(choices=[('pending', 'Afventer godkendelse'), ('approved', 'Godkendt'), ('rejected', 'Afvist')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oprettet')),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='Gør det muligt at se, hvor længe en anmodning har ventet.', null=True, verbose_name='status ændret')),
                ('review_note', models.TextField(blank=True, help_text='Intern note om beslutningen. Vises ikke for ansøgeren.', verbose_name='bemærkning')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signup_requests', to=settings.AUTH_USER_MODEL, verbose_name='behandlet af')),
                ('user', models.OneToOneField(blank=True, help_text='Den inaktive konto, anmodningen oprettede. Tom når anmodningen er afvist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to=settings.AUTH_USER_MODEL, verbose_name='bruger')),
            ],
            options={
                'verbose_name': 'brugeranmodning',
                'verbose_name_plural': 'brugeranmodninger',
                'ordering': ['-created_at'],
            },
        ),
    ]
