# Generated by Django 5.2.17 on 2026-09-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signuprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='claimed_resident_number',
            field=models.CharField(blank=True, help_text='Krævet på tilmeldingssiden, men bevidst ikke formatvalideret. Bruges til at finde personen i beboerregistret.', max_length=32, verbose_name='oplyst beboernummer'),
        ),
    ]
