# Generated by Django 5.2.17 on 2026-09-14 09:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_signuprequest_claimed_resident_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='external_user_id',
        ),
        migrations.AddField(
            model_name='resident',
            name='unit_number',
            field=models.CharField(blank=True, db_index=True, help_text='Bolignr. i beboerregistret. Format: 1-1121-4203.', max_length=16, validators=[django.core.validators.RegexValidator(message='Bolignummer skal have formatet 1-1121-4203.', regex='^\\d-\\d{3,5}-\\d{3,5}$')], verbose_name='unit number'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_number',
            field=models.CharField(blank=True, db_index=True, help_text='Beboernr. i beboerregistret. Format: 1-2345-6789-0. Deles af en husstand.', max_length=16, validators=[django.core.validators.RegexValidator(message='Beboernummer skal have formatet 1-2345-6789-0.', regex='^\\d-\\d{3,5}-\\d{3,5}-\\d{1,3}$')], verbose_name='resident number'),
        ),
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(db_index=True, help_text='Enheden — lejligheden, butikken eller rummet. Ændrer sig ikke.', max_length=16, validators=[django.core.validators.RegexValidator(message='Bolignummer skal have formatet 1-1121-4203.', regex='^\\d-\\d{3,5}-\\d{3,5}$')], verbose_name='bolignr.')),
                ('name_key', models.CharField(help_text='Navnet i sammenlignbar form. Sammen med bolignr. identificerer det rækken.', max_length=300, verbose_name='navnenøgle')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='fornavn')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='efternavn')),
                ('alias', models.CharField(blank=True, help_text='Kaldenavn eller firmanavn, som registret skriver det.', max_length=200, verbose_name='alias')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('role', models.CharField(blank=True, db_index=True, help_text="'Role hos CS': Juridisk navn/bruger, Husstandsmedlem, Fremlejertager, …", max_length=64, verbose_name='rolle')),
                ('unit_type', models.CharField(blank=True, db_index=True, help_text='Andelsbolig, Erhverv, Loft/Kælder/Depotrum. Tom for husstandsmedlemmer.', max_length=64, verbose_name='enhedstype')),
                ('resident_number', models.CharField(blank=True, db_index=True, help_text='Lejemålet. Deles af husstanden, og tomt for husstandsmedlemmer.', max_length=16, validators=[django.core.validators.RegexValidator(message='Beboernummer skal have formatet 1-2345-6789-0.', regex='^\\d-\\d{3,5}-\\d{3,5}-\\d{1,3}$')], verbose_name='beboernr.')),
                ('raw_address', models.CharField(blank=True, help_text='Ordret som registret skriver den, også når den ikke kunne læses.', max_length=255, verbose_name='adresse i registret')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='postnr.')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='by')),
                ('floor', models.CharField(blank=True, max_length=8, verbose_name='etage')),
                ('door', models.CharField(blank=True, max_length=16, verbose_name='dør')),
                ('moved_in', models.DateField(blank=True, help_text='Kan ligge i fremtiden. Har bevidst ingen betydning for, om kontoen kan aktiveres.', null=True, verbose_name='indflytningsdato')),
                ('is_eligible', models.BooleanField(db_index=True, default=False, help_text='Bor i en andelsbolig ifølge sidste import. Sat af importen, ikke i hånden.', verbose_name='kan aktivere konto')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Falsk når rækken er forsvundet fra registret — typisk en fraflytning.', verbose_name='står i seneste udtræk')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='set første gang')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Det seneste udtræk, personen faktisk stod i.', verbose_name='set sidste gang')),
                ('source_row', models.PositiveIntegerField(blank=True, help_text='Kun til fejlsøgning i den downloadede fil.', null=True, verbose_name='linje i udtrækket')),
                ('building', models.ForeignKey(blank=True, help_text='Tom når adressen ikke kunne læses — typisk et kælder- eller depotrum.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_entries', to='accounts.building', verbose_name='opgang')),
            ],
            options={
                'verbose_name': 'beboerregisterrække',
                'verbose_name_plural': 'beboerregister',
                'ordering': ['unit_number', 'name_key'],
                'constraints': [models.UniqueConstraint(fields=('unit_number', 'name_key'), name='unique_register_entry_per_unit_and_name')],
            },
        ),
    ]
