# Generated by Django 5.2.17 on 2026-09-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resident_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerentry',
            options={'ordering': ['unit_number', 'name_key'], 'permissions': [('import_register', 'Kan importere beboerregistret fra en fil')], 'verbose_name': 'beboerregisterrække', 'verbose_name_plural': 'beboerregister'},
        ),
    ]
